name: Run quack game
on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  run_quack:
    runs-on: ubuntu-latest
    env:
      QUACK_TOKEN: ${{ secrets.QUACK_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5
      - name: Setup NodeJS 20
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x
      - name: Run code
        run: |
          npm install
          node quack.js
